server:
  #port: ${PORT:0}
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:flightinformationbooking
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    
  h2:
    console:
      enabled: true
      path: /h2Console

eureka:  instance:    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:    service-url: 
      defaultZone: http://192.168.0.117:8761/eureka/
    healthcheck:      enabled: true
    
   
flight:
  #url: http://localhost:8089/flightStatus
  url: http://flight-service/flightStatus